apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ingress-nginx
  namespace: argocd-system
spec:
  project: platform-dev-mgmt
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx 
      targetRevision: "4.10.1"
      helm:
        valueFiles:
        - $values/Nginx-Ingress/Platform/dev/internal-ingress-nginx.yaml
    - repoURL: ssh://git@GITLAB_OR_GITHUB:2222/devops/oss-helm-values.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx