apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    env: prod
    platform: ct
    region: asia-northeast3
    service: grafana    
  name: backendconfig-grafana-server
  namespace: grafana-system
spec:
  healthCheck:
    checkIntervalSec: 30
    healthyThreshold: 1
    timeoutSec: 5
    type: HTTP
    unhealthyThreshold: 2
    port: 3000
    requestPath: /login
  logging:
    enable: true
    sampleRate: 1
  securityPolicy:
    name: cap-mkt-prod-observability-tools
  sessionAffinity:
    affinityType: CLIENT_IP
  timeoutSec: 3600
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  labels:
    env: prod
    platform: ct
    region: asia-northeast3  
    service: grafana  
  name: frontendconfig-grafana-server
  namespace: grafana-system
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
  sslPolicy: computesslpolicy-grafana-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: EXTERNAL_IP
    networking.gke.io/v1beta1.FrontendConfig: FRONTENDCONFIG_NAME
    ingress.gcp.kubernetes.io/pre-shared-cert: "SELF_SIGNED_CERT"
  labels:
    env: prod
    platform: ct
    region: asia-northeast3
    service: grafana    
  name: elb-mkt-prod-wish-grafana
  namespace: grafana-system
spec:
  rules:
  - host: grafana.wemakeprice.cloud
    http:
      paths:
      - backend:
          service:
            name: grafana-server
            port:
              number: 3000
        path: "/"
        #pathType: ImplementationSpecific
        pathType: Prefix
